// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/solo-kit-example/simple/api/shapes.proto

// proto package should match group name

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CircleSpec struct {
	Radius               float32  `protobuf:"fixed32,1,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleSpec) Reset()         { *m = CircleSpec{} }
func (m *CircleSpec) String() string { return proto.CompactTextString(m) }
func (*CircleSpec) ProtoMessage()    {}
func (*CircleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_9228c6ff7acded61, []int{0}
}
func (m *CircleSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleSpec.Unmarshal(m, b)
}
func (m *CircleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleSpec.Marshal(b, m, deterministic)
}
func (m *CircleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleSpec.Merge(m, src)
}
func (m *CircleSpec) XXX_Size() int {
	return xxx_messageInfo_CircleSpec.Size(m)
}
func (m *CircleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_CircleSpec proto.InternalMessageInfo

func (m *CircleSpec) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type CircleStatus struct {
	Area                 float32  `protobuf:"fixed32,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircleStatus) Reset()         { *m = CircleStatus{} }
func (m *CircleStatus) String() string { return proto.CompactTextString(m) }
func (*CircleStatus) ProtoMessage()    {}
func (*CircleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9228c6ff7acded61, []int{1}
}
func (m *CircleStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircleStatus.Unmarshal(m, b)
}
func (m *CircleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircleStatus.Marshal(b, m, deterministic)
}
func (m *CircleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircleStatus.Merge(m, src)
}
func (m *CircleStatus) XXX_Size() int {
	return xxx_messageInfo_CircleStatus.Size(m)
}
func (m *CircleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CircleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CircleStatus proto.InternalMessageInfo

func (m *CircleStatus) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

type SquareSpec struct {
	Width                float32  `protobuf:"fixed32,1,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareSpec) Reset()         { *m = SquareSpec{} }
func (m *SquareSpec) String() string { return proto.CompactTextString(m) }
func (*SquareSpec) ProtoMessage()    {}
func (*SquareSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_9228c6ff7acded61, []int{2}
}
func (m *SquareSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareSpec.Unmarshal(m, b)
}
func (m *SquareSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareSpec.Marshal(b, m, deterministic)
}
func (m *SquareSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareSpec.Merge(m, src)
}
func (m *SquareSpec) XXX_Size() int {
	return xxx_messageInfo_SquareSpec.Size(m)
}
func (m *SquareSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareSpec.DiscardUnknown(m)
}

var xxx_messageInfo_SquareSpec proto.InternalMessageInfo

func (m *SquareSpec) GetWidth() float32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type SquareStatus struct {
	Area                 float32  `protobuf:"fixed32,1,opt,name=area,proto3" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SquareStatus) Reset()         { *m = SquareStatus{} }
func (m *SquareStatus) String() string { return proto.CompactTextString(m) }
func (*SquareStatus) ProtoMessage()    {}
func (*SquareStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9228c6ff7acded61, []int{3}
}
func (m *SquareStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SquareStatus.Unmarshal(m, b)
}
func (m *SquareStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SquareStatus.Marshal(b, m, deterministic)
}
func (m *SquareStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SquareStatus.Merge(m, src)
}
func (m *SquareStatus) XXX_Size() int {
	return xxx_messageInfo_SquareStatus.Size(m)
}
func (m *SquareStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SquareStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SquareStatus proto.InternalMessageInfo

func (m *SquareStatus) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func init() {
	proto.RegisterType((*CircleSpec)(nil), "simple.skv2.solo.io.CircleSpec")
	proto.RegisterType((*CircleStatus)(nil), "simple.skv2.solo.io.CircleStatus")
	proto.RegisterType((*SquareSpec)(nil), "simple.skv2.solo.io.SquareSpec")
	proto.RegisterType((*SquareStatus)(nil), "simple.skv2.solo.io.SquareStatus")
}

func init() {
	proto.RegisterFile("github.com/solo-io/solo-kit-example/simple/api/shapes.proto", fileDescriptor_9228c6ff7acded61)
}

var fileDescriptor_9228c6ff7acded61 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xbd, 0x4e, 0xc4, 0x30,
	0x10, 0x84, 0x15, 0x04, 0x29, 0x56, 0x54, 0x06, 0x21, 0x4a, 0x64, 0x51, 0xd0, 0xc4, 0x56, 0xa0,
	0xa4, 0x83, 0x07, 0x40, 0x90, 0x8e, 0x6e, 0x93, 0x58, 0xf1, 0x2a, 0x8e, 0x6c, 0xfc, 0x13, 0xee,
	0xf1, 0x4f, 0x89, 0xdd, 0x9d, 0xae, 0xb8, 0x6a, 0x76, 0xb4, 0xdf, 0x8e, 0x34, 0x0b, 0xef, 0x13,
	0x45, 0x9d, 0x7a, 0x31, 0xd8, 0x45, 0x06, 0x6b, 0x6c, 0x43, 0x36, 0xeb, 0x4c, 0xb1, 0x51, 0x07,
	0x5c, 0x9c, 0x51, 0x32, 0xd0, 0x2e, 0xe8, 0x48, 0x06, 0x8d, 0x4e, 0x05, 0xe1, 0xbc, 0x8d, 0x96,
	0xdd, 0xe5, 0x85, 0x08, 0xf3, 0xfa, 0x2a, 0xb6, 0x2b, 0x41, 0x96, 0x3f, 0x03, 0x7c, 0x92, 0x1f,
	0x8c, 0xea, 0x9c, 0x1a, 0xd8, 0x03, 0xd4, 0x1e, 0x47, 0x4a, 0xe1, 0xb1, 0x7a, 0xaa, 0x5e, 0xae,
	0x7e, 0x8a, 0xe3, 0x1c, 0x6e, 0x0b, 0x15, 0x31, 0xa6, 0xc0, 0x18, 0x5c, 0xa3, 0x57, 0x58, 0xa8,
	0x7d, 0xe6, 0x1c, 0xa0, 0xfb, 0x4b, 0xe8, 0x73, 0xd2, 0x3d, 0xdc, 0xfc, 0xd3, 0x18, 0x75, 0x41,
	0xb2, 0xd9, 0x72, 0x0a, 0x73, 0x36, 0xe7, 0xe3, 0xfb, 0xf7, 0xeb, 0x82, 0x96, 0x6e, 0x9e, 0x72,
	0xd3, 0xd3, 0x6e, 0x72, 0x6d, 0xd1, 0x38, 0x8d, 0x6d, 0x5f, 0xef, 0x0f, 0x78, 0x3b, 0x06, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0x58, 0x34, 0xb4, 0x3f, 0x01, 0x00, 0x00,
}
