// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/solo-kit-example/simple/api/shapes.proto

// proto package should match group name

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for CircleSpec
func (this *CircleSpec) MarshalJSON() ([]byte, error) {
	str, err := ShapesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CircleSpec
func (this *CircleSpec) UnmarshalJSON(b []byte) error {
	return ShapesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CircleStatus
func (this *CircleStatus) MarshalJSON() ([]byte, error) {
	str, err := ShapesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CircleStatus
func (this *CircleStatus) UnmarshalJSON(b []byte) error {
	return ShapesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SquareSpec
func (this *SquareSpec) MarshalJSON() ([]byte, error) {
	str, err := ShapesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SquareSpec
func (this *SquareSpec) UnmarshalJSON(b []byte) error {
	return ShapesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SquareStatus
func (this *SquareStatus) MarshalJSON() ([]byte, error) {
	str, err := ShapesMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SquareStatus
func (this *SquareStatus) UnmarshalJSON(b []byte) error {
	return ShapesUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ShapesMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	ShapesUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{}
)
