// Code generated by skv2. DO NOT EDIT.

// This file contains generated Deepcopy methods for simple.skv2.solo.io/v1alpha1 resources

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// Generated Deepcopy methods for Circle

func (in *Circle) DeepCopyInto(out *Circle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

func (in *Circle) DeepCopy() *Circle {
	if in == nil {
		return nil
	}
	out := new(Circle)
	in.DeepCopyInto(out)
	return out
}

func (in *Circle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CircleList) DeepCopyInto(out *CircleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Circle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

func (in *CircleList) DeepCopy() *CircleList {
	if in == nil {
		return nil
	}
	out := new(CircleList)
	in.DeepCopyInto(out)
	return out
}

func (in *CircleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// Generated Deepcopy methods for Square

func (in *Square) DeepCopyInto(out *Square) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

func (in *Square) DeepCopy() *Square {
	if in == nil {
		return nil
	}
	out := new(Square)
	in.DeepCopyInto(out)
	return out
}

func (in *Square) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SquareList) DeepCopyInto(out *SquareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Square, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

func (in *SquareList) DeepCopy() *SquareList {
	if in == nil {
		return nil
	}
	out := new(SquareList)
	in.DeepCopyInto(out)
	return out
}

func (in *SquareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
